import test from 'node:test';import assert from 'node:assert/strict';
import {newGame,bid,play,aiView,chooseMove,deck,type Game,type Difficulty} from './engine';
import {encode,cardVector,roleFor} from './douzero';
import {rankHeuristic,bidFor,styleScore,handCost} from './strategy';
import {SoundSystem} from './audio';
function fixture(){let g=newGame(()=>.1);return bid(g,g.turn,3);}
test('model rank and seat encodings, including both jokers and two',()=>{const d=deck();assert.deepEqual(cardVector(d),Array(54).fill(1));assert.equal(cardVector(d.filter(c=>c.rank===15)).slice(48,52).join(''),'1111');let g=fixture();for(let seat=0;seat<3;seat++){const v=aiView(g,seat),e=encode(v);assert.equal(e.width,seat===g.landlord?373:484);assert.equal(e.z.length,810);assert.equal(e.x.length,e.width*e.moves.length);assert.equal(roleFor(v),seat===g.landlord?'landlord':seat===(g.landlord+1)%3?'landlord_down':'landlord_up');}});
test('history survives UI truncation, passes encoded and hidden allocation never exposed',()=>{let g=fixture();for(let i=0;i<21;i++)g=play(g,g.turn,g.target?[]:[g.hands[g.turn][0].id]);assert.ok(g.history.length>12);assert.ok(g.events.length<=12);const seat=g.turn,a=aiView(g,seat),others=[0,1,2].filter(i=>i!==seat);const hands=g.hands.map(h=>[...h]);[hands[others[0]][0],hands[others[1]][0]]=[hands[others[1]][0],hands[others[0]][0]];assert.deepEqual(aiView({...g,hands},seat),a);const v={...a,history:[...a.history,{seat:others[0],kind:'pass' as const,cards:[],text:'不出'}]};assert.ok(encode(v).z.slice(-54).every(x=>x===0));});
test('all difficulties take an immediate win and never propose illegal IDs',()=>{const g=fixture();for(const difficulty of ['casual','standard','expert'] as Difficulty[]){const h=g.hands[0].slice(0,1);const v=aiView({...g,turn:0,target:null,hands:[h,g.hands[1],g.hands[2]]},0);assert.deepEqual(rankHeuristic(v,difficulty,()=>.5)[0].ids,h.map(c=>c.id));}});
test('character styles are distinct and landlord bids react to temperament',()=>{const g=fixture(),v=aiView(g,0),cards=deck().filter(c=>c.rank>=3&&c.rank<=7&&c.suit===0),p={kind:'straight' as const,rank:7,size:5};assert.ok(styleScore({...v,character:'rana'},cards,p)>styleScore({...v,character:'soyo'},cards,p));assert.ok(styleScore({...v,character:'anon'},[cards[0]],{kind:'single',rank:14,size:1})>styleScore({...v,character:'tomori'},[cards[0]],{kind:'single',rank:14,size:1}));assert.ok(bidFor({...v,character:'anon',bid:0},'standard')>=bidFor({...v,character:'tomori',bid:0},'standard'));assert.equal(handCost([]),0);});
test('parallel audio starts immediately, ducks until all finish and stops every voice',async()=>{
 const made:any[]=[];class MockAudio{src='';volume=1;loop=false;onended:any;onerror:any;plays=0;paused=false;constructor(src=''){this.src=src;made.push(this);}play(){this.plays++;return Promise.resolve();}pause(){this.paused=true;}}
 (globalThis as any).Audio=MockAudio;(globalThis as any).AudioContext=class{resume(){return Promise.resolve();}};const s=new SoundSystem();s.start();let starts=0;const a=s.speak('a',()=>starts++),b=s.speak('b',()=>starts++),c=s.speak('c',()=>starts++);assert.equal(starts,3);assert.equal(s.activeVoiceCount,3);assert.ok(made.slice(1).every(x=>x.plays===1));assert.equal(made[0].volume,.22*.38);made[1].onended();assert.equal(s.activeVoiceCount,2);assert.equal(made[0].volume,.22*.38);s.configure({music:.5,voice:.3,sfx:0,muted:true});assert.ok(made.slice(2).every(x=>x.volume===0));s.configure({music:.5,voice:.3,sfx:0,muted:false});assert.ok(made.slice(2).every(x=>x.volume===.3));s.stopVoice();assert.equal(s.activeVoiceCount,0);assert.equal(made[0].volume,.5);assert.deepEqual(await Promise.all([a,b,c]),[true,false,false]);});
test('AI worker timeout releases pending request and restarts cleanly',async()=>{const {AIClient}=await import('./ai-client');let workers=0,terminated=0;class FakeWorker{onmessage:any;onerror:any;constructor(){workers++;}postMessage(data:any){if(workers>1)queueMicrotask(()=>this.onmessage({data:{id:data.id,type:'decision',decision:{gameId:data.view.gameId,revision:data.view.revision,actions:[],difficulty:'standard'}}}));}terminate(){terminated++;}}
 (globalThis as any).Worker=FakeWorker;const client=new AIClient(),v=aiView(fixture(),0);await assert.rejects(client.decide(v,'expert'),/超时/);assert.equal(terminated,1);const result=await client.decide(v,'standard');assert.equal(result.gameId,v.gameId);assert.equal(result.revision,v.revision);client.dispose();});
test('standard hints preserve bombs and straights when a clean response exists',()=>{
 const get=(rs:number[])=>{const d=deck(),used=new Set<number>();return rs.map(r=>{const c=d.find(c=>c.rank===r&&!used.has(c.id))!;used.add(c.id);return c;});};
 const g=fixture(),v=aiView(g,0),target={cards:get([3]),pattern:{kind:'single' as const,rank:3,size:1},seat:1};
 for(const rs of [[6,6,6,6,9,11],[4,5,6,7,8,10]]){const hand=get(rs),view={...v,hand,target,seat:0,landlord:1,lastSeat:1,counts:[hand.length,12,12]};const ids=rankHeuristic(view,'standard')[0].ids;const picked=hand.filter(c=>ids.includes(c.id));assert.equal(picked.length,1);assert.ok(picked[0].rank>=9,`should keep the ${rs.length===6?'combination':'structure'} intact`);}
});
