import type {Card} from './engine';
import {packs,shuffled} from './parlor-engine';
export type BJAction='hit'|'stand'|'double'|'split';
export type BJHand={cards:Card[];bet:number;done:boolean;split:boolean;delta:number};
export type Blackjack={id:number;revision:number;shoe:Card[];dealer:Card[];hands:BJHand[];active:number;phase:'play'|'done';exposed:Card[];delta:number};
export const point=(c:Card)=>c.rank===14?11:c.rank===15?2:Math.min(c.rank,10);
export function total(cs:Card[]){let value=cs.reduce((n,c)=>n+point(c),0),aces=cs.filter(c=>c.rank===14).length;while(value>21&&aces){value-=10;aces--;}return {value,soft:aces>0};}
const natural=(cs:Card[])=>cs.length===2&&total(cs).value===21;
function finish(s:Blackjack){if(s.hands.some(h=>total(h.cards).value<=21&&(!natural(h.cards)||h.split))&&!natural(s.dealer))while(total(s.dealer).value<17)s.dealer.push(s.shoe.pop()!);const d=total(s.dealer).value;s.phase='done';s.hands=s.hands.map(h=>{const p=total(h.cards).value;const delta=p>21?-h.bet:natural(s.dealer)?natural(h.cards)&&!h.split?0:-h.bet:natural(h.cards)&&!h.split?h.bet*1.5:d>21||p>d?h.bet:p===d?0:-h.bet;return {...h,done:true,delta};});s.delta=s.hands.reduce((n,h)=>n+h.delta,0);return s;}
export function newBlackjack(random=Math.random,previous?:Blackjack):Blackjack{const reuse=previous&&previous.shoe.length>=78,shoe=reuse?[...previous.shoe]:shuffled(packs(6,false),random);const s:Blackjack={id:Date.now()+Math.floor(random()*10000),revision:0,shoe,dealer:[],hands:[{cards:[],bet:2,done:false,split:false,delta:0}],active:0,phase:'play',exposed:reuse?[...previous.exposed,...previous.dealer,...previous.hands.flatMap(h=>h.cards)]:[],delta:0};for(let i=0;i<2;i++){s.hands[0].cards.push(shoe.pop()!);s.dealer.push(shoe.pop()!);}if(natural(s.dealer)||natural(s.hands[0].cards))finish(s);return s;}
export function bjActions(s:Pick<Blackjack,'phase'|'hands'|'active'>):BJAction[]{if(s.phase!=='play')return [];const h=s.hands[s.active];return ['hit','stand',...(h.cards.length===2?['double']:[]),...(s.hands.length===1&&h.cards.length===2&&h.cards[0].rank===h.cards[1].rank?['split']:[])] as BJAction[];}
export function bjPlay(state:Blackjack,action:BJAction){if(!bjActions(state).includes(action))throw Error('现在不能执行该操作');const s=structuredClone(state),h=s.hands[s.active];s.revision++;if(action==='split'){const a=h.cards[0],b=h.cards[1];s.hands=[a,b].map(c=>({cards:[c,s.shoe.pop()!],bet:2,done:c.rank===14,split:true,delta:0}));if(a.rank===14)return finish(s);return s;}if(action==='hit'||action==='double'){h.cards.push(s.shoe.pop()!);if(action==='double')h.bet*=2;if(action==='double'||total(h.cards).value>=21)h.done=true;}else h.done=true;if(h.done){const next=s.hands.findIndex(x=>!x.done);if(next===-1)return finish(s);s.active=next;}return s;}
// This view never exposes the dealer hole card or the future order of the shoe.
export function bjView(s:Blackjack){return {phase:s.phase,hands:s.hands,active:s.active,dealer:s.dealer[0],exposed:[...s.exposed,...s.hands.flatMap(h=>h.cards),s.dealer[0]]};}
export type BJView=ReturnType<typeof bjView>;
export function bjBasic(v:BJView):BJAction{const h=v.hands[v.active],p=total(h.cards),d=point(v.dealer),allowed=bjActions(v);if(allowed.includes('split')){const r=point(h.cards[0]);if(r===11||r===8||r===9&&![7,10,11].includes(d)||r===7&&d<=7||r===6&&d<=6||[2,3].includes(r)&&d<=7||r===4&&[5,6].includes(d))return 'split';}if(p.soft){if(p.value>=19)return 'stand';if(allowed.includes('double')&&((p.value===18&&d>=3&&d<=6)||(p.value===17&&d>=3&&d<=6)||([15,16].includes(p.value)&&d>=4&&d<=6)||([13,14].includes(p.value)&&d>=5&&d<=6)))return 'double';return p.value===18&&d<=8?'stand':'hit';}if(allowed.includes('double')&&(p.value===11&&d!==11||p.value===10&&d<=9||p.value===9&&d>=3&&d<=6))return 'double';if(p.value>=17||p.value>=13&&d<=6||p.value===12&&d>=4&&d<=6)return 'stand';return 'hit';}
