import test from 'node:test';
import assert from 'node:assert/strict';
import {deck,classify,beats,legalMoves,newGame,bid,play,aiView,chooseBid,chooseMove,type Card,type Kind,type Game,useSkill,skillBudget,autoSkill} from './engine';
const cards=(ranks:number[]):Card[]=>{const d=deck(),used=new Set<number>();return ranks.map(r=>{const c=d.find(c=>c.rank===r&&!used.has(c.id));assert.ok(c,`invalid fixture rank ${r}`);used.add(c.id);return c;});};
const cases:[Kind,number[]][]=[['single',[3]],['pair',[4,4]],['triple',[5,5,5]],['tripleOne',[6,6,6,3]],['triplePair',[6,6,6,3,3]],['straight',[10,11,12,13,14]],['pairs',[3,3,4,4,5,5]],['plane',[3,3,3,4,4,4]],['planeOne',[3,3,3,4,4,4,5,5]],['planePair',[3,3,3,4,4,4,5,5,6,6]],['fourTwo',[3,3,3,3,4,4]],['fourPairs',[3,3,3,3,4,4,5,5]],['bomb',[15,15,15,15]],['rocket',[16,17]]];
for(const [kind,rs] of cases)test(`recognizes ${kind}`,()=>{assert.equal(classify(cards(rs))?.kind,kind);assert.ok(legalMoves(cards(rs)).some(m=>m.cards.length===rs.length&&m.pattern.kind===kind));});
test('invalid and ambiguous boundaries',()=>{for(const rs of [[11,12,13,14,15],[3,4,5,6],[3,3,4,4],[3,3,3,4,4,4,16,17],[3,3,3,3,4,4,4,5],[3,3,3,3,16,17],[3,3,3,3,4,4,4,4],[14,14,14,15,15,15]])assert.equal(classify(cards(rs)),null,rs.join(','));assert.equal(classify([deck()[0],deck()[0]]),null);});
test('comparison respects type, length, bombs, rocket and primary rank',()=>{const p=(r:number[])=>classify(cards(r))!;assert.ok(beats(p([4]),p([3])));assert.ok(!beats(p([4,4]),p([3])));assert.ok(!beats(p([4,5,6,7,8,9]),p([3,4,5,6,7])));assert.ok(beats(p([3,3,3,3]),p([17])));assert.ok(beats(p([16,17]),p([15,15,15,15])));assert.ok(!beats(p([15,15,15,15]),p([16,17])));assert.ok(beats(p([6,6,6,3]),p([5,5,5,17])));});
test('bidding, dealer ownership and three-pass redeal',()=>{let g=newGame(()=>.4);const first=g.turn;g=bid(g,g.turn,0);g=bid(g,g.turn,0);const oldId=g.id;g=bid(g,g.turn,0);assert.notEqual(g.id,oldId);assert.equal(g.phase,'bid');assert.deepEqual(g.hands.map(h=>h.length),[17,17,17]);g=bid(g,g.turn,3);assert.equal(g.phase,'play');assert.equal(g.hands[g.landlord].length,20);assert.equal(g.turn,g.landlord);assert.throws(()=>bid(g,first,1));let x=newGame(()=>.5);x=bid(x,x.turn,1);assert.throws(()=>bid(x,x.turn,1));x=bid(x,x.turn,2);x=bid(x,x.turn,0);assert.equal(x.bid,2);});
test('two passes reset the trick, leading pass is rejected, invalid actions do not mutate',()=>{let g=newGame(()=>.3);g=bid(g,g.turn,3);assert.throws(()=>play(g,g.turn,[]));const leader=g.turn;const id=g.hands[leader][0].id;const before=JSON.stringify(g);assert.throws(()=>play(g,(leader+1)%3,[id]));assert.equal(JSON.stringify(g),before);g=play(g,leader,[id]);g=play(g,g.turn,[]);assert.equal(g.passes,1);g=play(g,g.turn,[]);assert.equal(g.target,null);assert.equal(g.turn,leader);assert.equal(g.passes,0);assert.throws(()=>play(g,leader,[id]));});
function fixture(landlord:number,hands:number[][],played=[0,0,0]):Game{const g=newGame();return {...g,phase:'play',landlord,turn:0,bid:2,hands:hands.map(cards),played};}
test('landlord spring, anti-spring, ordinary farmer win and bomb accounting',()=>{let g=fixture(0,[[3],[4],[5]]);g=play(g,0,g.hands[0].map(c=>c.id));assert.equal(g.spring,'春天');assert.deepEqual(g.delta,[8,-4,-4]);g=fixture(1,[[3],[4],[5]],[1,1,1]);g=play(g,0,g.hands[0].map(c=>c.id));assert.equal(g.spring,'反春天');assert.deepEqual(g.delta,[4,-8,4]);g=fixture(1,[[3],[4],[5]],[1,2,1]);g=play(g,0,g.hands[0].map(c=>c.id));assert.equal(g.spring,'');assert.deepEqual(g.delta,[2,-4,2]);g=fixture(0,[[3,3,3,3],[4],[5]],[1,1,1]);g=play(g,0,g.hands[0].map(c=>c.id));assert.equal(g.bombs,1);assert.deepEqual(g.delta,[8,-4,-4]);assert.throws(()=>play(g,1,[]));});
function seeded(seed:number){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
test('rank enumerator agrees with brute-force subsets for varied small hands',()=>{for(let seed=1;seed<=35;seed++){const h=newGame(seeded(seed)).hands[0].slice(0,11);const expected=new Set<string>();for(let mask=1;mask<(1<<h.length);mask++){const cs=h.filter((_,i)=>(mask>>i)&1);if(classify(cs))expected.add(cs.map(c=>c.rank).sort((a,b)=>a-b).join(','));}const actual=new Set(legalMoves(h).map(m=>m.cards.map(c=>c.rank).sort((a,b)=>a-b).join(',')));assert.deepEqual(actual,expected);}});
test('100 complete AI games: legal moves, card conservation, termination, zero-sum',()=>{let steps=0;const wins=[0,0,0];for(let seed=1;seed<=100;seed++){let g=newGame(seeded(seed));let turns=0;while(g.phase!=='done'&&turns++<400){const v=aiView(g,g.turn);assert.equal('hands' in v,false);if(g.phase==='bid')g=bid(g,g.turn,chooseBid(v));else{const move=chooseMove(v);if(move.length){const p=classify(move);assert.ok(p);assert.ok(beats(p,g.target?.pattern||null));}g=play(g,g.turn,move.map(c=>c.id));}const all=[...g.hands.flat(),...g.discard,...(g.phase==='bid'?g.bottom:[])];assert.equal(all.length,54);assert.equal(new Set(all.map(c=>c.id)).size,54);}assert.equal(g.phase,'done',`seed ${seed} exceeded ${turns} turns`);assert.equal(g.delta.reduce((a,b)=>a+b,0),0);assert.equal(g.hands[g.winner].length,0);wins[g.winner]++;steps+=turns;}console.log({games:100,turns:steps,wins});});

test('five skills reveal only defined public information, preserve turn and cards',()=>{
 for(const id of ['tomori','anon','rana','soyo','taki'] as const){let g=fixture(0,[[8],[3,3,3,3,4,5,6,7,16,17],[9,10,11,12,13,14]]);g={...g,mode:'skills',characters:[id,'rana','soyo']};const next=useSkill(g,0,1,g.hands[0].map(c=>c.id));assert.equal(next.turn,g.turn);assert.deepEqual(next.hands,g.hands);assert.equal(next.bombs,0);assert.deepEqual(next.delta,g.delta);assert.equal(next.skillUses[0],1);assert.equal(next.intel[0].value,{tomori:3,anon:1,rana:5,soyo:1,taki:3}[id]);assert.deepEqual(aiView(next,2).intel,next.intel);assert.throws(()=>useSkill(next,0,1,g.hands[0].map(c=>c.id)));}
});
test('skill budgets, enemy-only target, endgame protection and invalidation',()=>{
 let g:Game={...fixture(0,[[8],[3,4,5,6,7,9],[10,11,12,13,14,15]]),mode:'skills' as const};assert.deepEqual([0,1,2].map(i=>skillBudget(g,i)),[2,1,1]);assert.throws(()=>useSkill(g,1,2));assert.throws(()=>useSkill({...g,mode:'classic'},0,1));assert.throws(()=>useSkill({...g,hands:[g.hands[0],g.hands[1].slice(0,5),g.hands[2]]},0,1));g=useSkill(g,0,1);g=useSkill(g,0,2);assert.throws(()=>useSkill(g,0,1));const next=play({...g,turn:1},1,[g.hands[1][0].id]);assert.equal(next.intel.length,1);assert.equal(next.intel[0].target,2);
 let redeal=newGame(seeded(1),{mode:'skills',characters:['taki','rana','anon']});for(let i=0;i<3;i++)redeal=bid(redeal,redeal.turn,0);assert.equal(redeal.mode,'skills');assert.deepEqual(redeal.characters,['taki','rana','anon']);
});
test('paired role-balanced skill simulations terminate legally with conserved cards',()=>{
 const ids=['tomori','anon','rana','soyo','taki'] as const;const results=Object.fromEntries(ids.map(id=>[id,{classic:0,skills:0,n:0}]));let total=0;
 for(const a of ids)for(const b of ids)for(const c of ids){if(new Set([a,b,c]).size<3)continue;for(let seed=1;seed<=40;seed++)for(const mode of ['classic','skills'] as const){let g=newGame(seeded(seed),{mode,characters:[a,b,c]});g=bid({...g,turn:0},0,3);let turn=0;while(g.phase!=='done'&&turn++<400){const skill=autoSkill(g);g=skill??play(g,g.turn,chooseMove(aiView(g,g.turn)).map(c=>c.id));assert.equal(new Set([...g.hands.flat(),...g.discard].map(c=>c.id)).size,54);}assert.equal(g.phase,'done');assert.equal(g.delta.reduce((a,b)=>a+b,0),0);[a,b,c].forEach((id,i)=>{results[id][mode]+=Number(g.delta[i]>0);results[id].n+=Number(mode==='classic');});total++;}}
 console.log('Paired skill balance',JSON.stringify({total,results}));
});
