import type {VoiceEvent} from './voice-expansion';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {newParlor,pPlay,pMoves,pView,type PGame,type GameKind} from './parlor-engine';
import {newBlackjack,bjPlay,bjActions,bjView,bjBasic,total,type Blackjack,type BJAction} from './blackjack';
import {pickOpponents,type Character} from './characters';
import type {Difficulty,Card} from './engine';
import PlayingCard from './PlayingCard';
import Portrait from './Portrait';
import {sound} from './audio';
import {decideParlor} from './parlor-client';
const actionNames:Record<BJAction,string>={hit:'要牌',stand:'停牌',double:'加倍',split:'分牌'};
export const parlorRules={runfast:'三人各16张，保留黑桃2、去掉黑桃A。首副黑桃3先出，后续赢家先出。有牌必压，下家报单时单张必须出最大牌。支持单、对、三带二、顺子、连对、飞机带单与炸弹；最后一手可少带附件。两家不出重新领牌。剩1张免赔，全关翻倍；炸弹压住一轮每家另赔5分。',blackjack:'六副牌，庄家软17停牌。底注2分，天然21点赔3分，普通胜负2分，和局不计分。首两张可加倍，同点数可分牌一次，分牌后可加倍；分A各补一张，分牌21点按普通胜利结算。无保险、无投降。'};
export default function Parlor({kind,character,difficulty,speeches,onBack,onResetVoices,onVoice}:{kind:Exclude<GameKind,'doudizhu'>;character:Character;difficulty:Difficulty;speeches:Record<number,{jp:string;zh:string;address?:string}>;onBack:()=>void;onResetVoices:()=>void;onVoice:(c:Character,index:number,seat:number,event?:VoiceEvent,target?:Character)=>void}){
 const [members]=useState(()=>[character,...pickOpponents(character.id,kind==='runfast'?2:1)]);
 const [run,setRun]=useState<PGame>(()=>newParlor('runfast',Math.random,undefined,members.map(c=>c.id)));
 const [bj,setBj]=useState<Blackjack>(()=>newBlackjack());const [selected,setSelected]=useState<number[]>([]),[auto,setAuto]=useState(false),[message,setMessage]=useState(''),[rules,setRules]=useState(false),[leave,setLeave]=useState(false),[hint,setHint]=useState(0);
 const drag=useRef<{select:boolean;seen:Set<number>}|null>(null);
 useEffect(()=>{const move=(e:PointerEvent)=>{const d=drag.current;if(!d)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-card-id]') as HTMLElement|null;const id=Number(el?.dataset.cardId);if(!el||d.seen.has(id))return;d.seen.add(id);setSelected(v=>d.select?[...new Set([...v,id])]:v.filter(x=>x!==id));};const up=()=>{drag.current=null;};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);};},[]);
 const [busy,setBusy]=useState(false);const current=useRef<{id:number;revision:number}>({id:0,revision:0});
 const [stats,setStats]=useState(()=>{try{return JSON.parse(localStorage.getItem(`parlor-${kind}-stats`)||'{"score":0,"games":0}');}catch{return {score:0,games:0};}});
 const state=kind==='runfast'?run:bj;current.current={id:state.id,revision:state.revision};const scored=useRef(new Set<number>());const hand=kind==='runfast'?run.hands[0]:bj.hands[bj.active].cards;const myTurn=state.phase==='play'&&(kind==='blackjack'||run.turn===0)&&!auto;
 useEffect(()=>{if(state.phase!=='done'||scored.current.has(state.id))return;scored.current.add(state.id);const delta=kind==='runfast'?run.delta[0]:bj.delta;setStats((v:{score:number;games:number})=>{const next={score:v.score+delta,games:v.games+1};localStorage.setItem(`parlor-${kind}-stats`,JSON.stringify(next));return next;});sound.effect(delta>0?'win':'pass');onVoice(character,delta>0?13:14,0,delta>0?"win":"lose");},[state.id,state.phase]);
 function act(ids:number[]|BJAction){try{if(kind==='runfast'){const next=pPlay(run,0,ids as number[]);setRun(next);if(next.phase!=='done')onVoice(character,(ids as number[]).length?2:3,0,(ids as number[]).length?"play":"pass");}else {const next=bjPlay(bj,ids as BJAction);setBj(next);if(next.phase!=='done')onVoice(character,ids==='stand'?20:19,0,ids==='stand'?'pass':'play');}setSelected([]);setHint(0);setMessage('');sound.effect('play');}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{if(rules||leave||state.phase==='done'||(kind==='runfast'?run.turn===0&&!auto:!auto))return;let canceled=false;const snapshot={id:state.id,revision:state.revision};const t=setTimeout(async()=>{const answer=await decideParlor({...snapshot,difficulty,...(kind==='runfast'?{run:pView(run,members[run.turn].id)}:{blackjack:bjView(bj)})});if(canceled||current.current.id!==answer.id||current.current.revision!==answer.revision)return;if(kind==='runfast'){const next=pPlay(run,run.turn,answer.actions[0]?.ids||[]);setRun(next);if(next.phase!=='done')onVoice(members[run.turn],answer.actions[0]?.ids.length?2:3,run.turn,answer.actions[0]?.ids.length?"play":"pass");}else setBj(s=>bjPlay(s,answer.blackjack!));sound.effect('play');},650);return()=>{canceled=true;clearTimeout(t);};},[run,bj,auto,rules,leave]);
 async function showHint(){setBusy(true);const answer=await decideParlor({id:state.id,revision:state.revision,difficulty,...(kind==='runfast'?{run:pView(run,character.id)}:{blackjack:bjView(bj)})});setBusy(false);if(current.current.id!==answer.id||current.current.revision!==answer.revision)return;if(kind==='runfast'){setSelected(answer.actions[hint%answer.actions.length]?.ids||[]);setHint(v=>v+1);}else setMessage(`建议：${actionNames[answer.blackjack!]}`);}

 const lastInteraction=useRef(0);
 function interact(){if(Date.now()-lastInteraction.current<8000)return;lastInteraction.current=Date.now();onVoice(character,10,0,"chat",members[1]);onVoice(members[1],11,1,"reply",character);}
 function again(){onResetVoices();setRun(s=>newParlor('runfast',Math.random,s,members.map(c=>c.id)));setBj(s=>newBlackjack(Math.random,s));setSelected([]);setMessage('');setHint(0);onVoice(character,19,0,"table");}
 const row=(cs:Card[],hide=false)=><div className="parlor-cards">{cs.map((c,i)=><PlayingCard key={c.id} card={hide&&i===1?undefined:c} small/>)}</div>;
 const runfastTable=kind==='runfast'?<>
 <div className="table-top"><button className="text-button" onClick={()=>state.phase==='done'?onBack():setLeave(true)}>← 返回大厅</button><div className="bottom-cards"><span>跑得快</span><span>积分 <b>{stats.score}</b></span></div><button className="text-button" onClick={()=>setRules(true)}>规则</button></div>
 <div className="table-ellipse"><div className="table-watermark">✧<span>迷星牌局</span><small>LET OUR STARS ALIGN</small></div></div>
 {[2,1].map(seat=><div key={seat} className={`opponent opponent-${seat} ${run.turn===seat&&run.phase!=='done'?'thinking':''}`}><div className="opponent-frame"><Portrait id={members[seat].id} alt={members[seat].name}/><span className="role-badge">{seat===2?'上家':'下家'}</span></div><div className="opponent-caption"><b>{members[seat].name}</b><small>{run.turn===seat&&run.phase!=='done'?'思考中…':'等待出牌'}</small></div><div className={`card-count ${run.hands[seat].length<=2?'danger':''}`}><span>▱</span> {run.hands[seat].length}<small>张</small></div>{speeches[seat]&&<div className="speech-bubble">{speeches[seat].address&&<small className="speech-name">{speeches[seat].address}</small>}<span>{speeches[seat].jp}</span><small>{speeches[seat].zh}</small></div>}</div>)}
 <section className="table-center" aria-live="polite"><div className="turn-label"><span className="live-dot"/>{run.phase==='done'?'本局合奏结束':run.turn===0?(auto?'自动出牌中':`${character.name} 的回合`):`${members[run.turn].name} 的回合`}</div>{run.target?<div className="last-play"><div className="played-cards" style={{'--played-count':run.target.cards.length,'--played-cols':Math.min(10,run.target.cards.length),'--played-rows':Math.ceil(run.target.cards.length/10)} as CSSProperties}>{run.target.cards.map((c,i)=><PlayingCard key={c.id} card={c} small style={{'--played-i':i,'--played-col':i%10,'--played-row':Math.floor(i/10)} as CSSProperties}/>)}</div><p>{members[run.last].name} <span>· {run.target.pattern.kind}</span></p></div>:<div className="free-lead"><span>✧</span><p>自由领出</p></div>}<div className="pass-history">{run.history.slice(-run.passes||run.history.length).filter(e=>!e.cards.length).map((e,i)=><span key={i}>{members[e.seat].name} · 不出</span>)}</div></section>
 <section className="player-zone"><div className="player-info"><Portrait id={character.id}/><div><b>{character.name}<span>操作中</span></b><small>{hand.length} 张</small></div><div className="player-utilities"><button className={`auto-button ${auto?'enabled':''}`} disabled={run.phase==='done'} onClick={()=>{setAuto(v=>!v);setSelected([]);}}>{auto?'取消托管':'托管'}</button><button className="chat-button" onClick={()=>interact()}>♪ 互动</button></div></div>
 <div className="action-row">{run.phase==='play'&&(myTurn?<><button disabled={!run.target||pMoves(run).length>0} onClick={()=>act([])}>不出</button><button disabled={busy} onClick={showHint}>{busy?'思考中…':'提示'}</button><button disabled={!selected.length} onClick={()=>setSelected([])}>取消选择</button><button className="primary" disabled={!selected.length} onClick={()=>act(selected)}>出牌 {selected.length>0&&<small>{selected.length}</small>}</button></>:<span className="waiting-label">{auto?'自动出牌中':'等待其他成员出牌…'}</span>)}</div>
 <div className="hand-caption" role="status">{message||(selected.length?`已选 ${selected.length} 张`:'点击或滑动选择手牌')}<span>{!run.target&&myTurn?'本轮领出':''}</span></div>
 <div className="hand" style={{'--count':hand.length} as CSSProperties}>{hand.map((c,i)=><PlayingCard key={c.id} card={c} selected={selected.includes(c.id)} style={{'--i':i} as CSSProperties} disabled={!myTurn} data-card-id={c.id} onPointerDown={e=>{if(!myTurn)return;e.preventDefault();const choose=!selected.includes(c.id);drag.current={select:choose,seen:new Set([c.id])};setSelected(v=>choose?[...new Set([...v,c.id])]:v.filter(id=>id!==c.id));}} onClick={e=>{if(myTurn&&e.detail===0)setSelected(v=>v.includes(c.id)?v.filter(id=>id!==c.id):[...v,c.id]);}}/>)}</div>
 {speeches[0]&&<div className="player-subtitle"><span>{speeches[0].address&&<small className="speech-name">{speeches[0].address}</small>}{speeches[0].jp}<small>{speeches[0].zh}</small></span></div>}</section>
 </>:null;
 return <main className={kind==='runfast'?'table-screen runfast-table':'parlor-table parlor-blackjack'} data-phase={state.phase} data-turn={run.turn}>{kind==='runfast'?runfastTable:<>
<div className="parlor-top"><button onClick={()=>state.phase==='done'?onBack():setLeave(true)}>← 返回大厅</button><b>二十一点 · {stats.score} 分</b><button onClick={()=>setRules(true)}>规则</button></div>
 <div className="parlor-opponents">{members.slice(1).map((c,j)=><article key={c.id}><Portrait id={c.id}/><b>{c.name}</b>{speeches[j+1]&&<div className="parlor-speech">{speeches[j+1].jp}<small>{speeches[j+1].zh}</small></div>}<span>庄家</span></article>)}</div>
 <section className="parlor-center">{row(bj.dealer,bj.phase==='play')}<p>庄家 · {bj.phase==='done'?`${total(bj.dealer).value} 点${total(bj.dealer).value>21?' · 爆牌':''}`:`明牌 ${total([bj.dealer[0]]).value} 点 · 停牌后揭牌`}</p><div className="bj-hands">{bj.hands.map((h,i)=><div className={i===bj.active?'active':''} key={i}>{row(h.cards)}<p>{bj.hands.length>1?`第 ${i+1} 手 · `:''}{total(h.cards).value} 点 · {h.bet} 分{h.done?' · 已停牌':''}</p></div>)}</div></section>
 {bj.phase!=='done'&&<section className="parlor-player">{speeches[0]&&<div className="parlor-own-speech">{speeches[0].jp}<small>{speeches[0].zh}</small></div>}<div className="parlor-player-label"><b>{character.name}</b><button onClick={()=>{setAuto(v=>!v);setSelected([]);}}>{auto?'取消托管':'托管'}</button><button onClick={()=>interact()}>♪ 互动</button></div><div className="parlor-actions">{(['hit','stand','double','split'] as BJAction[]).map(a=><button key={a} disabled={!myTurn||!bjActions(bj).includes(a)} onClick={()=>act(a)}>{actionNames[a]}</button>)}<button disabled={!myTurn||busy} onClick={showHint}>提示</button></div><p className="parlor-message" role="status">{message||' '}</p></section>}</>}
 {state.phase==='done'&&<div className={`parlor-result ${kind==='blackjack'?'blackjack-result':''}`} role="status"><h2>{(kind==='runfast'?run.delta[0]:bj.delta)>0?'漂亮的合奏':(kind==='runfast'?run.delta[0]:bj.delta)===0?'平分秋色':'下一曲，再来'}</h2><strong>{kind==='runfast'?run.delta[0]:bj.delta} 分</strong>{kind==='blackjack'&&<p>庄家 {total(bj.dealer).value} 点 · {character.name} {bj.hands.map(h=>`${total(h.cards).value} 点`).join(' / ')}</p>}<div><button onClick={onBack}>返回大厅</button><button className="primary" onClick={again}>再来一局</button></div></div>}
 {(rules||leave)&&<div className="modal-backdrop"><section className="modal"><h2>{rules?'玩法规则':'返回大厅？'}</h2><p>{rules?parlorRules[kind]:'当前对局将结束，不计入积分。'}</p><button onClick={()=>{setRules(false);setLeave(false);}}>继续对局</button>{leave&&<button onClick={onBack}>返回大厅</button>}</section></div>}
 </main>;
}
