import {deck,sortCards,classify,legalMoves,type Card,type Difficulty,type CharacterId} from './engine';
export type GameKind='doudizhu'|'runfast'|'blackjack';
export const gameNames:Record<GameKind,string>={doudizhu:'斗地主',runfast:'跑得快',blackjack:'二十一点'};
export type PPattern={kind:string;size:number;rank:number;tie:number[];power:number};
export type PMove={cards:Card[];pattern:PPattern};
export type PEvent={seat:number;cards:Card[];text:string};
export type PGame={id:number;revision:number;kind:Exclude<GameKind,'doudizhu'|'blackjack'>;hands:Card[][];turn:number;target:PMove|null;last:number;passes:number;history:PEvent[];discard:Card[];order:number[];phase:'play'|'done';delta:number[];first:boolean;characters:CharacterId[];notice:string};
export function shuffled(cards:Card[],random=Math.random){const a=[...cards];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function packs(n:number,jokers=true){return Array.from({length:n},(_,pack)=>deck().filter(c=>jokers||c.rank<16).map(c=>({...c,id:pack*54+c.id,pack}))).flat();}
const group=(cs:Card[])=>{const m=new Map<number,Card[]>();for(const c of cs)m.set(c.rank,[...(m.get(c.rank)||[]),c]);return m;};
const make=(kind:string,size:number,rank:number,power=0,tie:number[]=[]):PPattern=>({kind,size,rank,power,tie});
export function comparePattern(a:PPattern,b:PPattern){if(a.power!==b.power)return a.power-b.power;if(a.kind!==b.kind||a.size!==b.size)return -999;for(const [x,y] of [[a.rank,b.rank],...a.tie.map((x,i)=>[x,b.tie[i]||0])])if(x!==y)return x-y;return 0;}
export function pClassify(_kind:PGame['kind'],cs:Card[],_level=15,lastHand=false):PPattern|null{if(!cs.length||new Set(cs.map(c=>c.id)).size!==cs.length)return null;const g=group(cs);if(cs.length===5){const triple=[...g.entries()].find(([,v])=>v.length===3);if(triple)return make('三带二',5,triple[0]);}if(lastHand){const ranks=[...g.entries()].filter(([,v])=>v.length===3).map(([r])=>r).sort((a,b)=>a-b);if(ranks.length>=2&&ranks.at(-1)!<=14&&ranks.every((r,i)=>!i||r===ranks[i-1]+1)&&cs.length<=ranks.length*4)return make('飞机带单',cs.length,ranks.at(-1)!);}const p=classify(cs);if(!p)return null;const names:Record<string,string>={single:'单张',pair:'对子',triplePair:'三带二',straight:'顺子',pairs:'连对',planeOne:'飞机带单',bomb:'炸弹'};if(names[p.kind])return make(names[p.kind],cs.length,p.rank,p.kind==='bomb'?4:0);if(lastHand&&['triple','tripleOne','plane'].includes(p.kind))return make(p.kind==='plane'?'飞机带单':'三带二',cs.length,p.rank);return null;}
export function pBeats(a:PPattern,b:PPattern|null,_kind:PGame['kind']){if(!b)return true;if(a.power||b.power)return a.power>b.power||(a.power===b.power&&a.kind===b.kind&&a.size===b.size&&comparePattern(a,b)>0);return a.kind===b.kind&&a.size===b.size&&comparePattern(a,b)>0;}
export function pMoves(s:Pick<PGame,'kind'|'hands'|'turn'|'target'|'first'>):PMove[]{const h=s.hands[s.turn],out:PMove[]=[];const add=(cs:Card[])=>{const p=pClassify(s.kind,cs,15,cs.length===h.length);if(!p||!pBeats(p,s.target?.pattern||null,s.kind))return;if(s.first&&!cs.some(c=>c.rank===3&&c.suit===0))return;if(cs.length===1&&s.hands[(s.turn+1)%3].length===1&&cs[0].rank<Math.max(...h.map(c=>c.rank)))return;if(!out.some(m=>m.cards.map(c=>c.id).sort().join()===cs.map(c=>c.id).sort().join()))out.push({cards:sortCards(cs),pattern:p});};for(const m of legalMoves(h))add(m.cards);const g=group(h);for(const [r,cs] of g)if(cs.length>=3){const rest=h.filter(c=>c.rank!==r);for(let i=0;i<rest.length;i++)for(let j=i+1;j<rest.length;j++)add([...cs.slice(0,3),rest[i],rest[j]]);}add(h);return out;}
export function newParlor(kind:PGame['kind'],random=Math.random,previous?:PGame,characters:CharacterId[]=[]):PGame{const cards=shuffled(packs(1,false).filter(c=>!(c.rank===15&&c.suit!==0)&&!(c.rank===14&&c.suit===0)),random);const hands=Array.from({length:3},(_,i)=>sortCards(cards.slice(i*16,(i+1)*16)));const turn=previous?.order[0]??hands.findIndex(h=>h.some(c=>c.rank===3&&c.suit===0));return {id:Date.now()+Math.floor(random()*10000),revision:0,kind,hands,turn,target:null,last:turn,passes:0,history:[],discard:[],order:[],phase:'play',delta:[0,0,0],first:!previous,characters,notice:''};}
export function pPlay(s:PGame,seat:number,ids:number[]):PGame{if(s.phase!=='play'||s.turn!==seat)throw Error('尚未轮到该角色');const cs=s.hands[seat].filter(c=>ids.includes(c.id));if(cs.length!==ids.length||new Set(ids).size!==ids.length)throw Error('选牌无效');const t=structuredClone(s);t.revision++;
 const settleBomb=()=>{if(t.target?.pattern.kind==='炸弹')for(let i=0;i<3;i++)t.delta[i]+=i===t.last?10:-5;};
 if(!ids.length){if(!s.target)throw Error('领出时不能不出');if(pMoves(s).length)throw Error('有牌必须压过');t.passes++;t.history.push({seat,cards:[],text:'不出'});if(t.passes===2){settleBomb();t.target=null;t.passes=0;t.turn=t.last;}else t.turn=(seat+1)%3;return t;}
 const p=pClassify(s.kind,cs,15,cs.length===s.hands[seat].length);if(!p||!pBeats(p,s.target?.pattern||null,s.kind))throw Error('牌型不符或未压过上家');if(s.first&&!cs.some(c=>c.rank===3&&c.suit===0))throw Error('首出必须包含黑桃 3');if(cs.length===1&&s.hands[(seat+1)%3].length===1&&cs[0].rank<Math.max(...s.hands[seat].map(c=>c.rank)))throw Error('下家报单，须出最大单张');
 t.first=false;t.hands[seat]=t.hands[seat].filter(c=>!ids.includes(c.id));t.discard.push(...cs);t.target={cards:sortCards(cs),pattern:p};t.last=seat;t.passes=0;t.history.push({seat,cards:cs,text:p.kind});t.turn=(seat+1)%3;
 if(!t.hands[seat].length){t.order=[seat];t.phase='done';settleBomb();for(let i=0;i<3;i++)if(i!==seat){const n=t.hands[i].length,cost=n===1?0:n===16?32:n;t.delta[i]-=cost;t.delta[seat]+=cost;}}return t;}
export type PView=Omit<PGame,'hands'> & {hand:Card[];counts:number[];character:CharacterId};
export function pView(s:PGame,character:CharacterId):PView{const {hands,...rest}=s;return {...rest,hand:hands[s.turn],counts:hands.map(h=>h.length),character};}
export function pRank(v:PView,difficulty:Difficulty,random=Math.random){const shell={...v,hands:v.counts.map((n,i)=>i===v.turn?v.hand:Array(n).fill({rank:0,id:-1,suit:0}))};const moves=pMoves(shell);const own=group(v.hand);const mate=false;const actions=moves.map(m=>{let score=m.cards.length*2-m.pattern.rank*.08;for(const [r,cs] of group(m.cards)){const size=own.get(r)!.length;if(cs.length<size)score-=size>=4?8:size===3?3:1;}if(m.pattern.power>=4)score-=4;if(mate)score-=7;if(['rana','mutsumi'].includes(v.character)&&['顺子','同花顺','三连对','两连三','连对','飞机带单'].includes(m.pattern.kind))score+=1.2;if(['soyo','sakiko'].includes(v.character)&&m.pattern.rank>=14)score-=1;if(['anon','nyamu'].includes(v.character))score+=.4;if(['taki','umiri'].includes(v.character))score+=m.cards.length*.15;if(difficulty==='casual')score+=random()*7;if(m.cards.length===v.hand.length)score=1e6;return {ids:m.cards.map(c=>c.id),score};});if(v.target&&(v.kind!=='runfast'||!moves.length))actions.push({ids:[],score:mate?1:-10});return actions.sort((a,b)=>b.score-a.score);}
