import {test} from 'node:test';import assert from 'node:assert/strict';
import {newParlor,pMoves,pPlay,pRank,pView,pClassify} from './parlor-engine';
import {newBlackjack,bjPlay,bjBasic,bjView,total,bjActions} from './blackjack';
import {deck} from './engine';
const random=(seed:number)=>()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return (seed>>>0)/4294967296;};
test('runfast 1000 games: legal termination, conservation, zero sum',()=>{for(let seed=0;seed<1000;seed++){const rng=random(seed);let s=newParlor('runfast',rng);assert.equal(s.hands.flat().length,48);for(let turn=0;s.phase!=='done';turn++){assert.ok(turn<500);const actions=pRank(pView(s,'tomori'),'standard',rng);assert.ok(actions.length);s=pPlay(s,s.turn,actions[0].ids);assert.equal(s.hands.flat().length+s.discard.length,48);assert.equal(new Set([...s.hands.flat(),...s.discard].map(c=>c.id)).size,48);}assert.equal(s.delta.reduce((a,b)=>a+b),0);}});
test('runfast must beat and opening includes spade three',()=>{let s=newParlor('runfast',random(123));assert.ok(pMoves(s).every(m=>m.cards.some(c=>c.rank===3&&c.suit===0)));assert.throws(()=>pPlay(s,s.turn,[]));s=pPlay(s,s.turn,pMoves(s)[0].cards.map(c=>c.id));if(pMoves(s).length)assert.throws(()=>pPlay(s,s.turn,[]));});
test('runfast rejects four with two and allows final triple',()=>{const d=deck();assert.equal(pClassify('runfast',[...d.slice(0,4),...d.slice(4,6)]),null);assert.ok(pClassify('runfast',d.slice(0,3),15,true));assert.equal(pClassify('runfast',d.slice(0,3)),null);});
test('blackjack 1000 games: bounded actions, conservation and hidden card excluded',()=>{for(let seed=0;seed<1000;seed++){let s=newBlackjack(random(seed));for(let t=0;s.phase==='play';t++){assert.ok(t<40);const view=bjView(s);assert.ok(!view.exposed.some(c=>c.id===s.dealer[1].id));const a=bjBasic(view);assert.ok(bjActions(s).includes(a));s=bjPlay(s,a);}const cards=[...s.shoe,...s.dealer,...s.hands.flatMap(h=>h.cards)];assert.equal(cards.length,312);assert.equal(new Set(cards.map(c=>c.id)).size,312);assert.ok(Number.isFinite(s.delta));}});
test('soft ace valuation',()=>{assert.deepEqual(total([{id:1,rank:14,suit:0},{id:2,rank:6,suit:0}]),{value:17,soft:true});assert.deepEqual(total([{id:1,rank:14,suit:0},{id:2,rank:14,suit:1},{id:3,rank:9,suit:0}]),{value:21,soft:true});});
import {newGame,bid,useSkill,skillNames,play,type CharacterId} from './engine';
import {rankRun} from './parlor-ai';
test('five Mujica skills reveal facts, preserve cards and expire',()=>{for(const id of ['uika','mutsumi','umiri','nyamu','sakiko'] as CharacterId[]){let s=newGame(random(35),{mode:'skills',characters:[id,'tomori','anon']});s.turn=0;s=bid(s,0,3);const before=s.hands.flat().map(c=>c.id).sort().join();if(id==='uika'){const d=deck();s.hands[0]=d.filter(c=>c.rank>=3&&c.rank<=7&&c.suit===0);s.hands[1]=d.filter(c=>c.rank>=8&&c.rank<=12&&c.suit===1).concat(d.filter(c=>c.rank===13));}const beforeSkill=s.hands.flat().map(c=>c.id).sort().join();const next=useSkill(s,0,1,id==='uika'?s.hands[0].map(c=>c.id):[]);assert.equal(next.turn,0);assert.equal(next.hands.flat().map(c=>c.id).sort().join(),beforeSkill);assert.equal(next.skillUses[0],1);assert.ok(next.intel[0].label);assert.ok(skillNames[id]);next.turn=1;next.target=null;const after=play(next,1,[next.hands[1][0].id]);assert.equal(after.intel.length,0);}});
test('blackjack split aces draws one; double ends hand',()=>{const c=(id:number,rank:number)=>({id,rank,suit:id%4});let s=newBlackjack(random(2));s.phase='play';s.hands=[{cards:[c(900,14),c(901,14)],bet:2,done:false,split:false,delta:0}];s.dealer=[c(902,10),c(903,7)];s.shoe=[c(904,10),c(905,9)];s=bjPlay(s,'split');assert.equal(s.phase,'done');assert.ok(s.hands.every(h=>h.cards.length===2&&h.split));assert.equal(s.delta,4);s=newBlackjack(random(3));s.phase='play';s.hands=[{cards:[c(900,5),c(901,6)],bet:2,done:false,split:false,delta:0}];s.dealer=[c(902,10),c(903,7)];s.shoe=[c(904,10)];s=bjPlay(s,'double');assert.equal(s.phase,'done');assert.equal(s.delta,4);});
test('all new difficulty decisions immediately finish using public input',()=>{const s=newParlor('runfast',random(1));s.first=false;s.turn=0;s.hands[0]=s.hands[0].slice(0,1);const v=pView(s,'sakiko');assert.ok(!('hands' in v));for(const d of ['casual','standard','expert'] as const)assert.deepEqual(rankRun(v,d)[0].ids,[s.hands[0][0].id]);});
test('Mutsumi and Mortis share skill budget and expose different boolean facts',()=>{let s=newGame(random(72),{mode:'skills',characters:['mutsumi','tomori','anon'],mutsumiFace:'quiet'});s.turn=0;s=bid(s,0,3);const quiet=useSkill(s,0,1);assert.match(quiet.intel[0].label,/静弦.*顺子/);const changed={...quiet,mutsumiFace:'mortis' as const};assert.throws(()=>useSkill(changed,0,1));const mortis=useSkill({...s,mutsumiFace:'mortis'},0,1);assert.match(mortis.intel[0].label,/戏弦.*飞机主体/);assert.equal(mortis.intel[0].query?.kind,'plane');assert.equal(mortis.skillUses[0],quiet.skillUses[0]);assert.equal(mortis.turn,quiet.turn);});

test('Uika asks a concrete multi-card question; reveals minimal higher main rank only',()=>{let s=newGame(random(9),{mode:'skills',characters:['uika','tomori','anon']});s.turn=0;s=bid(s,0,3);const d=deck();s.hands[0]=d.filter(c=>c.rank>=3&&c.rank<=7&&c.suit===0);s.hands[1]=d.filter(c=>c.rank>=6&&c.rank<=14&&c.suit===1);assert.throws(()=>useSkill(s,0,1,[s.hands[0][0].id]));const t=useSkill(s,0,1,s.hands[0].map(c=>c.id));assert.equal(t.intel[0].value,10);assert.equal(t.intel[0].query?.kind,'straight');assert.equal(t.turn,s.turn);assert.equal(t.skillUses[0],1);assert.throws(()=>useSkill({...s,hands:[s.hands[0],s.hands[1].slice(0,7),s.hands[2]]},0,1,s.hands[0].map(c=>c.id)));});
