import {pRank,pMoves,pPlay,pView,pBeats,pClassify,shuffled,packs,type PView,type PGame} from './parlor-engine';
import {bjBasic,bjActions,point,total,type BJView,type BJAction} from './blackjack';
import type {Difficulty,Card} from './engine';
export type ParlorRequest={id:number;revision:number;difficulty:Difficulty;run?:PView;blackjack?:BJView};
export type ParlorAnswer={id:number;revision:number;actions:{ids:number[];score:number}[];blackjack?:BJAction};
function leftoverCost(hand:Card[]){if(!hand.length)return 0;const counts=new Map<number,number>();for(const c of hand)counts.set(c.rank,(counts.get(c.rank)||0)+1);let turns=0;for(const copies of [1,2,3]){const min=copies===1?5:copies===2?3:2;let start=3;while(start<=14){let end=start;while(end<=14&&(counts.get(end)||0)>=copies)end++;if(end-start>=min){for(let r=start;r<end;r++)counts.set(r,counts.get(r)!-copies);turns++;}start=end>start?end:start+1;}}return turns+[...counts.values()].filter(n=>n>0).length;}
export function rankRun(v:PView,difficulty:Difficulty,random=Math.random,budget=500){let actions=pRank(v,difficulty,random);if(difficulty==='casual')return actions;actions=actions.map(a=>a.score>=1e6?a:{...a,score:a.score-leftoverCost(v.hand.filter(c=>!a.ids.includes(c.id)))*4}).sort((a,b)=>b.score-a.score);if(difficulty!=='expert'||actions[0]?.score>=1e6)return actions;
 const used=new Set([...v.hand,...v.history.flatMap(e=>e.cards)].map(c=>c.id));const unknown=packs(1,false).filter(c=>!(c.rank===15&&c.suit!==0)&&!(c.rank===14&&c.suit===0)&&!used.has(c.id));const start=performance.now(),top=actions.slice(0,4),scores=top.map(()=>0);let rounds=0;
 do{const sample=shuffled(unknown,random);const hands=v.counts.map((n,i)=>i===v.turn?v.hand:sample.splice(0,n));const rewards:number[]=[];for(let i=0;i<top.length;i++){let s:PGame={...v,hands:structuredClone(hands),characters:['tomori','anon','taki']};s=pPlay(s,s.turn,top[i].ids);let turns=0;while(s.phase==='play'&&turns++<70){const a=rankRun(pView(s,s.characters[s.turn]),'standard',random)[0];s=pPlay(s,s.turn,a.ids);}rewards.push(s.order[0]===v.turn?1:0);}for(let i=0;i<top.length;i++)scores[i]+=rewards[i];rounds++;}while(rounds<12&&performance.now()-start<budget);
 const best=scores.reduce((a,n,i)=>n>scores[a]?i:a,0);if(best!==0&&scores[best]-scores[0]>=Math.max(3,rounds*.34)){const winner=top[best];return [winner,...actions.filter(a=>a!==winner)];}return actions;

}
export function blackjackAdvice(v:BJView,difficulty:Difficulty,random=Math.random):BJAction{const basic=bjBasic(v);if(difficulty==='standard')return basic;const h=v.hands[v.active];if(difficulty==='casual'){const n=total(h.cards).value;return n>=17?'stand':'hit';}const allowed=bjActions(v);if(allowed.includes('split')&&basic==='split')return basic;
 const counts=Array(12).fill(0);for(const c of packs(6,false))counts[point(c)]++;for(const c of v.exposed)counts[point(c)]--;const n=counts.reduce((a,b)=>a+b,0),weights=counts.map(c=>c/n);
 const add=(value:number,soft:number,card:number)=>{value+=card;if(card===11)soft++;while(value>21&&soft){value-=10;soft--;}return [value,soft];};
 const dealerCache=new Map<string,number[]>();const dealer=(value:number,soft:number):number[]=>{const key=value+','+soft;if(dealerCache.has(key))return dealerCache.get(key)!;const out=Array(23).fill(0);if(value>=17){out[value>21?22:value]=1;return out;}for(let c=2;c<=11;c++)if(weights[c]){const [a,b]=add(value,soft,c),dist=dealer(a,b);for(let i=17;i<=22;i++)out[i]+=weights[c]*dist[i];}dealerCache.set(key,out);return out;};
 const distribution=Array(23).fill(0),up=point(v.dealer);let mass=0;for(let c=2;c<=11;c++){if((up===11&&c===10)||(up===10&&c===11))continue;const [a,b]=add(up,up===11?1:0,c);const dist=dealer(a,b);mass+=weights[c];for(let i=17;i<=22;i++)distribution[i]+=weights[c]*dist[i];}for(let i=17;i<=22;i++)distribution[i]/=mass;
 const stand=(value:number)=>value>21?-1:distribution.reduce((sum,p,d)=>sum+p*(d===22||value>d?1:value===d?0:-1),0);
 const cache=new Map<string,number>();const best=(value:number,soft:number):number=>{if(value>=21)return stand(value);const key=value+','+soft;if(cache.has(key))return cache.get(key)!;let hit=0;for(let c=2;c<=11;c++)if(weights[c]){const [a,b]=add(value,soft,c);hit+=weights[c]*best(a,b);}const out=Math.max(stand(value),hit);cache.set(key,out);return out;};
 const p=total(h.cards);let hit=0,double=0;for(let c=2;c<=11;c++)if(weights[c]){const [a,b]=add(p.value,p.soft?1:0,c);hit+=weights[c]*best(a,b);double+=weights[c]*stand(a)*2;}const scores:{action:BJAction;value:number}[]=[{action:'stand',value:stand(p.value)},{action:'hit',value:hit}];if(allowed.includes('double'))scores.push({action:'double',value:double});return scores.sort((a,b)=>b.value-a.value)[0].action;}

export function parlorDecision(q:ParlorRequest):ParlorAnswer{return {id:q.id,revision:q.revision,actions:q.run?rankRun(q.run,q.difficulty):[],blackjack:q.blackjack?blackjackAdvice(q.blackjack,q.difficulty):undefined};}
